# Railway Configuration for SPISA
# Documentation: https://docs.railway.app/deploy/config-as-code

# Backend Service Configuration
[[services]]
name = "spisa-backend"
source = "."
buildCommand = "cd backend/src/Spisa.WebApi && dotnet publish -c Release -o /app/publish"
startCommand = "cd /app/publish && dotnet Spisa.WebApi.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[services.env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:8080"

# Frontend Service Configuration  
[[services]]
name = "spisa-frontend"
source = "."
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[services.env]
NODE_ENV = "production"
PORT = "3000"


