-- SPISA Database Seed Data
-- Version: 2.0
-- Date: October 17, 2025
--
-- ⚠️ IMPORTANT: This seed file is now OPTIONAL
-- The migration tool (Spisa.DataMigration) will copy ALL data from the legacy
-- SPISA database including: provinces, tax conditions, operation types, 
-- payment methods, transporters, categories, articles, clients, orders, etc.
--
-- This file is ONLY needed for:
-- 1. Fresh installations without legacy data
-- 2. Default admin user creation (if not migrated from legacy)

-- ==============================================================================
-- DEFAULT ADMIN USER (Optional - for new installations)
-- ==============================================================================
-- Password: Admin123! (you should change this immediately after first login)
-- Hash generated with BCrypt
-- 
-- Only run this if you don't have users in the legacy system

-- INSERT INTO users (username, email, password_hash, full_name, role, is_active, created_at, updated_at) VALUES
--     ('admin', 'admin@spisa.local', '$2a$11$vXdK7kqX4h5fIVmGpY5mDeZLx5hCpRqQy7x5KqXcP5dM5JQVmH7qK', 'Administrator', 'ADMIN', TRUE, NOW(), NOW());

-- ==============================================================================
-- MIGRATION WORKFLOW
-- ==============================================================================
--
-- 1. Apply schema.sql to create empty tables
-- 2. Run Spisa.DataMigration tool to copy ALL data from legacy SPISA database
--    This includes:
--    - Provinces (from Provincias table)
--    - Tax Conditions (from CondicionesIVA table)
--    - Operation Types (from Operatorias table)
--    - Payment Methods (from FormasDePago table)
--    - Transporters (from Transportistas table)
--    - Categories (from Categorias table)
--    - Articles (from Articulos table)
--    - Clients (from Clientes table)
--    - Client Discounts (from Descuentos table)
--    - Sales Orders (from NotaPedidos table)
--    - Sales Order Items (from NotaPedido_Items table)
--    - Invoices (from Facturas table)
--    - Delivery Notes (from Remitos table)
--
-- 3. Verify data with the generated migration report
--
-- ==============================================================================

